### ISSUE TITLE
The training process will freeze if I use the logger

### ISSUE THREAD

**Issue by xugaoqi1993** [chenchens190009/KG-S2S#3]
Hello
I am trying to use the logger of pytorch lightning. However the training process will freeze in the middle. Is there any similar issues you have met when you were training this model? 
Thank you
<img width="1000" alt="1" src="https://user-images.githubusercontent.com/70183461/212615416-bea317b9-eeff-4bb2-9126-e0dfefe920ff.png">
<img width="1785" alt="1" src="https://user-images.githubusercontent.com/70183461/212615456-0ce659c1-e6d3-4629-a4e5-f2ff1896e11b.png">
<img width="1790" alt="1" src="https://user-images.githubusercontent.com/70183461/212615498-5229d06f-2d4f-42d8-80c6-6ca91189d8ff.png">

**Comment by chenchens190009** [comment]
I haven't used any built-in loggers of Pytorch Lightning. Not sure about the reason for this issue.
