### ISSUE TITLE
Question regarding the checkpoint

### ISSUE THREAD

**Issue by Tizzzzy** [chenchens190009/KG-S2S#4]
Hi,
After I download the checkpoint, the file is a .ckpt file. Do you know how to test this checkpoint on my testing data?

**Comment by chenchens190009** [comment]
Hi @Tizzzzy,

Thank you for your attention. 

There is an option `-model_path` where you can assign the path of the downloaded model. You can refer to the [evaluation commandline ](https://github.com/chenchens190009/KG-S2S#wn18rr) to evaluate the model. 

If you have your own testing data, please prepare them in the form of the dataset in our experiment, such as [WN18RR](https://github.com/chenchens190009/KG-S2S/tree/main/data/processed/WN18RR) and assign your dataset name (i.e. the folder name) with option `-dataset`.
