### ISSUE TITLE
Hello, how to solve the problem of error when running the code?

### ISSUE THREAD

**Issue by dbbice** [chenchens190009/KG-S2S#5]
Namespace(batch_size=64, dataset='WN18RR', dataset_path='./data/processed', decoder='beam_search', diversity_penalty=0.0, epochs=100
, eval_tgt_max_length=30, gpu='0', log_text=False, lr=0.001, model='T5Finetuner', model_dim=768, model_path='', n_ent=40943, n_rel=1
1, num_beam_groups=1, num_beams=40, num_workers=4, optim='Adam', pretrained_model='t5-base', save_dir='./checkpoint\\WN18RR-2023-10-
18 20-38-04', seed=41504, seq_dropout=0.1, skip_n_val_epoch=30, src_descrip_max_length=40, src_max_length=512, temporal=False, tgt_d
escrip_max_length=10, train_tgt_max_length=512, use_prefix_search=False, use_rel_prompt_emb=True, use_soft_prompt=True, val_batch_si
ze=8, vocab_size=32128)
Global seed set to 41504
tokenizing entities...
 35%|██████████████████████████████▍                                                        | 14332/40943 [00:29<00:53, 499.61it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████| 40943/40943 [01:24<00:00, 483.42it/s]
datamodule construction done.
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main()
  File "main.py", line 98, in main
    trainer = pl.Trainer(**trainer_params)
  File "D:\anaconda\envs\torch_1.12\lib\site-packages\pytorch_lightning\utilities\argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'checkpoint_callback'

**Comment by dbbice** [comment]
# 'checkpoint_callback': True,

I commented this line of code and the problem was solved~

**Comment by chenchens190009** [comment]
Cool~
