### ISSUE TITLE
problem of checkpoint

### ISSUE THREAD

**Issue by gyf6666** [chenchens190009/KG-S2S#8]
Dear author Hello, I can train normally and generate folders normally in the case of initial training ( there is no checkpoint file ), but I can 't save the model file. Can you help me
![QQ截图20240317220933](https://github.com/chenchens190009/KG-S2S/assets/148872612/55cc3900-b72d-4636-9baa-d7bc3fe943ac)

**Comment by ccchobits** [comment]
Hi @gyf6666, 

Thank you for your interest. The checkpoints will be stored after each evaluation on the validation set. By default, we skip a number of evaluation steps and set the evaluation frequency to 3, just to reduce the computation. We have two parameters to control the frequency of evaluation steps, i.e., 
`-skip_n_val_epoch`: You can change it in the commandline. 
`check_val_every_n_epoch`: You need to update it in main.py at line 91.
If you want to save the checkpoint from the first epoch, you need to set `-skip_n_val_epoch 0` and `check_val_every_n_epoch=1`

**Comment by gyf6666** [comment]
Thank you for your warm answer, I can now skillfully save checkpoints
